Operon\CoreBundle\Entity\Role:
  type: entity
  table: role
  fields:
    id:
      id: true
      type: integer
      unsigned: true
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 200
      fixed: false
      nullable: false
    exclusive:
      type: boolean
      nullable: false
    lft:
      type: integer
      unsigned: false
      nullable: false
    rgt:
      type: integer
      unsigned: false
      nullable: false
  manyToMany:
    item:
      targetEntity: Item
      cascade: {  }
      mappedBy: role
      inversedBy: null
      joinTable: null
      orderBy: null
  lifecycleCallbacks: {  }
